name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, linux]
        goarch: [amd64, arm64]
        include:
          - goos: windows
            ext: .exe
          - goos: linux
            ext: ''
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        go build -o dip${{ matrix.ext }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dip-${{ matrix.goos }}-${{ matrix.goarch }}
        path: dip${{ matrix.ext }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/dip-windows-amd64/dip.exe
          artifacts/dip-windows-arm64/dip.exe
          artifacts/dip-linux-amd64/dip
          artifacts/dip-linux-arm64/dip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}